spring:
  ai:
    openai:
      api-key: YOUR_OPENAI_API_KEY

  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:hospitaldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: "change-me-to-a-very-long-secret"
    expiration-ms: 3600000
  # openai, ai, powerbi configs for future use
  openai:
    api-key: "${OPENAI_API_KEY:}"
  ai:
    default-provider: LANGCHAIN4J # or SPRING_AI
  powerbi:
    client-id: "your-powerbi-client-id"
    client-secret: "your-powerbi-client-secret"
    tenant-id: "your-azure-tenant-id"
    workspace-id: "your-powerbi-workspace-id"
    dataset-name-prefix: "Hospital_Reports_"
